name: Collect Release Stats

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:
  release:
    types: [published]

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run stats collector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x .github/scripts/collect-stats.sh
          .github/scripts/collect-stats.sh
          
      - name: Verify stats.json
        run: |
          echo "Generated stats.json:"
          cat stats.json
          [ -f "stats.json" ] || exit 1
          
      - name: Commit and push stats
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          git add stats.json
          git commit -m "Update release statistics"
          git push
