name: Collect Release Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в 00:00
  workflow_dispatch:
  release:
    types: [published]

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run stats collector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Проверяем существование скрипта
          if [ ! -f ".github/scripts/collect-stats.sh" ]; then
            echo "Error: Script not found at .github/scripts/collect-stats.sh"
            exit 1
          fi
          
          # Убедимся, что скрипт исполняемый
          chmod +x .github/scripts/collect-stats.sh
          
          # Запускаем скрипт
          .github/scripts/collect-stats.sh
          
          # Проверяем результат
          cat stats.json
          cat historical_data.json

      - name: Verify files
        run: |
          [ -f "stats.json" ] || exit 1
          [ -f "historical_data.json" ] || exit 1
          echo "Files exist"

      - name: Commit and push stats
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add stats.json
          git add historical_data.json
          
          # Проверяем изменения
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update release statistics and historical data"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          fi
